type: 'baseline'

data:
    fraction: 1.0               # fraction of data-set to use at all
    split: 1            # fraction of data-set to retain labels
    val_frac: 0.2
    u_frac: -1
    fri_R: -1                  # fraction of unlabelled data-set to contain FR1
    l: 'all'              # dataset options: confident, uncertain, all, test, rgz
    u: 'all'              # dataset options: confident, uncertain, all, test, rgz

model:
    n_z: 32                     # latent vector length
    n_gf: 16                    # generator feature map size
    n_df: 16                    # discriminator feature map size
    architecture: 'tang'

train:
    n_epochs: 500
    fid: False
    flip: 0

seed: null

# optimisable hyperparams
cut_threshold: 29
cutout: 0
mu: 7
lambda: 1
tau: 0.95
p-strong: 1
lr: 0.0005
batch_size: 50
