type: 'fixmatch'

data:
    fraction: 1.0               # fraction of data-set to use at all
    split: 0.1                # fraction of data-set to retain labels
    val_frac: 0.2
    u_frac: 10
    fri_R: -1                   # fraction of unlabelled data-set to contain FR1
    l: 'all'              # dataset options: confident, uncertain, all, test, rgz
    u: 'all'              # dataset options: confident, uncertain, all, test, rgz
    seed: 5

model:
    n_z: 32                     # latent vector length
    n_gf: 16                    # generator feature map size
    n_df: 16                    # discriminator feature map size
    architecture: 'tang'

train:
    n_epochs: 500
    fid: False
    flip: 0

# optimisable hyperparams
cut_threshold: 29
cutout: 180
mu: 18
lambda: 1
tau: 0.92
p-strong: 0.8
lr: 0.0006
batch_size: 30 
