type: 'fixmatch'

data:
    fraction: 1.0
    split: 0.2 
    val_frac: 0.2
    u_frac: 7
    fri_R: -1
    l: 'confident'
    u: 'rgz'

model:
    n_z: 32                        # latent vector length
    n_gf: 16                       # generator feature map size
    n_df: 16                       # discriminator feature map size
    architecture: 'tang'

train:
    n_epochs: 1
    lr: 0.0001
    batch_size: 30 
    fid: False
    flip: 0
    p-strong: 0.5

cut_threshold: 22
ent_weight: 0
mu: -1
lambda: 1
tau: 0.9
