method: 'fixmatch'
data_source: 'gz_mnist'
project_name: 'ssl'
seed_i: 0
seed_f: 1
data:
    n_labels: 2
    fraction: 1.0  
    split: 0.05
    val_frac: 0.1
    u_frac: -1
    fri_R: -1
    labelled: 'all'              
    unlabelled: 'all'                   
    clamp_unlabelled: 0

model:
    n_df: 16                  

train:
    n_epochs: 800
    flip: 0
    label_weighting: False

seed: null

###############################
### optimisable hyperparams ###
###############################
n_aug: 2
m_aug: 10 
cut_threshold: 23
cutout: 0
crop: False
center_crop: 90
random_crop_min: 0.25 
random_crop_max: 0.8
mu: 7
lambda: 1
tau: 0.95
p-strong: 1
lr: 0.0005
batch_size: 20
# std: 0 
